# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbsettings.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dbsettings.proto',
  package='meteo.settings',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x64\x62settings.proto\x12\x0emeteo.settings\"\xe2\x01\n\x0c\x44\x62\x43onnection\x12\x11\n\tconn_name\x18\x01 \x02(\t\x12\x12\n\nhuman_name\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x02(\t\x12\x17\n\x04host\x18\x04 \x02(\t:\tlocalhost\x12\x12\n\x04port\x18\x05 \x01(\x05:\x04\x35\x34\x33\x32\x12\x13\n\x05login\x18\x06 \x01(\t:\x04root\x12\x10\n\x08password\x18\x07 \x01(\t\x12\x15\n\x06userdb\x18\x08 \x01(\t:\x05\x61\x64min\x12\x32\n\x08\x64\x62\x64river\x18\t \x01(\x0e\x32\x18.meteo.settings.DbDriver:\x06kMongo\"u\n\nDbSettings\x12\x33\n\rdb_connection\x18\x01 \x03(\x0b\x32\x1c.meteo.settings.DbConnection\x12\x32\n\x08\x64\x62\x64river\x18\x02 \x01(\x0e\x32\x18.meteo.settings.DbDriver:\x06kMongo*!\n\x08\x44\x62\x44river\x12\n\n\x06kMongo\x10\x01\x12\t\n\x05kPsql\x10\x02'
)

_DBDRIVER = _descriptor.EnumDescriptor(
  name='DbDriver',
  full_name='meteo.settings.DbDriver',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='kMongo', index=0, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='kPsql', index=1, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=384,
  serialized_end=417,
)
_sym_db.RegisterEnumDescriptor(_DBDRIVER)

DbDriver = enum_type_wrapper.EnumTypeWrapper(_DBDRIVER)
kMongo = 1
kPsql = 2



_DBCONNECTION = _descriptor.Descriptor(
  name='DbConnection',
  full_name='meteo.settings.DbConnection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='conn_name', full_name='meteo.settings.DbConnection.conn_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='human_name', full_name='meteo.settings.DbConnection.human_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='meteo.settings.DbConnection.name', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='host', full_name='meteo.settings.DbConnection.host', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=True, default_value=b"localhost".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='meteo.settings.DbConnection.port', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=5432,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='login', full_name='meteo.settings.DbConnection.login', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"root".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='meteo.settings.DbConnection.password', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userdb', full_name='meteo.settings.DbConnection.userdb', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"admin".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dbdriver', full_name='meteo.settings.DbConnection.dbdriver', index=8,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=263,
)


_DBSETTINGS = _descriptor.Descriptor(
  name='DbSettings',
  full_name='meteo.settings.DbSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='db_connection', full_name='meteo.settings.DbSettings.db_connection', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dbdriver', full_name='meteo.settings.DbSettings.dbdriver', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=265,
  serialized_end=382,
)

_DBCONNECTION.fields_by_name['dbdriver'].enum_type = _DBDRIVER
_DBSETTINGS.fields_by_name['db_connection'].message_type = _DBCONNECTION
_DBSETTINGS.fields_by_name['dbdriver'].enum_type = _DBDRIVER
DESCRIPTOR.message_types_by_name['DbConnection'] = _DBCONNECTION
DESCRIPTOR.message_types_by_name['DbSettings'] = _DBSETTINGS
DESCRIPTOR.enum_types_by_name['DbDriver'] = _DBDRIVER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DbConnection = _reflection.GeneratedProtocolMessageType('DbConnection', (_message.Message,), {
  'DESCRIPTOR' : _DBCONNECTION,
  '__module__' : 'dbsettings_pb2'
  # @@protoc_insertion_point(class_scope:meteo.settings.DbConnection)
  })
_sym_db.RegisterMessage(DbConnection)

DbSettings = _reflection.GeneratedProtocolMessageType('DbSettings', (_message.Message,), {
  'DESCRIPTOR' : _DBSETTINGS,
  '__module__' : 'dbsettings_pb2'
  # @@protoc_insertion_point(class_scope:meteo.settings.DbSettings)
  })
_sym_db.RegisterMessage(DbSettings)


# @@protoc_insertion_point(module_scope)
