######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 27 17:22:39 2017
######################################################################

TEMPLATE = lib
TARGET = meteodatawrap
DEPENDPATH += .
INCLUDEPATH += .

LIBS += -lmeteodata

# Input
SOURCES += meteo_data_wrap.cpp

include( $$(SRC)/include.pro )

LIBS += $$L_BOOST_PYTHON
