######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 27 17:29:50 2017
######################################################################

TEMPLATE = lib
TARGET = zondwrap
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -lzond


# Input
HEADERS += .
SOURCES += zondwrap.cpp         \

include( $$(SRC)/include.pro )

LIBS += $$L_BOOST_PYTHON
