SELECT meteo.add_station( @station@, 
                          @station_type@,
                          @index@,
                          @name@,
                          @source@,
                          @alt@,
                          @last_update@,
                          @last_used@,
                          @check@,
                          @operational@,
                          @location@,
                          @water_depth@,
                          @country@,
                          @hydro_levels@,
                          @airstrip_direction@);
