SELECT * FROM meteo.get_tlg( @id@, @t1@, @t2@, @a1@, @a2@, @cccc@, @bbb@,
                             @ii@, @yygggg@, @type@, @decoded@, @start_msgdt@,
                 @end_msgdt@, @start_dt@, @end_dt@, @sort@, @limit@, @skip@ )
         AS ( _id bigint,
              t1 text,
              t2 text,
              a1 text,
              a2 text,
              ii integer,
              cccc text,
              dddd text,
              bbb text,
              yygggg text,
              dt timestamp without time zone,
              msg_dt timestamp without time zone,
              md5 text,
              decoded boolean,
              external boolean,
              prior integer,
              bin boolean,
              format text,
              type text,
              size integer,
              file_id bigint,
              globalfile_id integer,
              addr_tlg boolean,
              confirm_tlg boolean,
              route jsonb,
              dup integer,
              cor_number integer,
              confirm boolean );
