select meteo.insert_sigwx( @dt@,
                           @center@,
                           @level_type@,
                           @level_lo@,
                           @level_hi@,
                           @descriptor@,
                           @value@,
                           @data_type@,
                           @source@,
                           @ii@,
                           @fileid@,
                           @tlgid@,
                           @dt_beg@,
                           @dt_end@ )
