select * from meteo.update_station( @id@ ,
                                    @cccc@,
                                    @stationindex@,
                                    @station@,
                                    @nameru@,
                                    @nameshort@,
                                    @nameen@,
                                    @stationtype@,
                                    @location@,
                                    @alt@,
                                    @poima@,
                                    @zatop@,
                                    @dangerlevel@,
                                    @direction@,
                                    @country@,
                                    @lastupdate@);

